[package]
name = "alloc-wg"
version = "0.1.0"
authors = ["Tim Diekmann <tim.diekmann@3dvision.de>"]
edition = "2018"
description = "Attempt of collection several proposals of the allocators-wg"
repository = "https://code.phase-engine.com/source/memory/"
readme = "README.md"
keywords = ["alloc"]
categories = ["data-structures"]
license = "MIT OR Apache-2.0"
