name: Documentation

on:
  push:
    branches:
      - master

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        run: rustup default nightly

      - name: Checkout source code
        uses: actions/checkout@master

      - name: Build documentation
        run: |
          cargo doc --no-deps
          echo '<meta http-equiv="refresh" content="0; url=alloc_wg">' > target/doc/index.html
          touch target/doc/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.GH_PAT }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: target/doc
