name: Documentation

on:
  push:
    branches:
      - master

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup default nightly

      - name: Checkout source code
        uses: actions/checkout@master

      - name: Build documentation
        run: |
          cargo doc --no-deps
          echo '<meta http-equiv="refresh" content="0; url=alloc_wg">' > target/doc/index.html
          touch target/doc/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.GH_PAT }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: target/doc
