name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        cargo_flags:
          - ""
          - "--no-default-features"
    steps:
      - name: Checkout the source code
        uses: actions/checkout@master

      - name: Install Rust nightly
        run: rustup default nightly

      - name: Build
        run: cargo build --all ${{ matrix.cargo_flags }}

      - name: Test
        run: cargo test --all ${{ matrix.cargo_flags }}
